cargo-features = ["per-package-target"]

[package]
name = "uprogs"
description = "octox user programs"
authors = ["Hayato Ohhashi <o8@vmm.dev>"]
edition = "2021"
version.workspace = true
license.workspace = true
repository.workspace = true
forced-target = "riscv64gc-unknown-none-elf"

[lib]
name = "ulib"
path = "lib/lib.rs"

[[bin]]
name = "_cat"
path = "bin/cat.rs"

[[bin]]
name = "_echo"
path = "bin/echo.rs"

[[bin]]
name = "_grep"
path = "bin/grep.rs"

[[bin]]
name = "_init"
path = "bin/init.rs"

[[bin]]
name = "_initcode"
path = "bin/initcode.rs"

[[bin]]
name = "_kill"
path = "bin/kill.rs"

[[bin]]
name = "_ln"
path = "bin/ln.rs"

[[bin]]
name = "_ls"
path = "bin/ls.rs"

[[bin]]
name = "_mkdir"
path = "bin/mkdir.rs"

[[bin]]
name = "_rm"
path = "bin/rm.rs"

[[bin]]
name = "_sh"
path = "bin/sh.rs"

[[bin]]
name = "_wc"
path = "bin/wc.rs"

[[bin]]
name = "_head"
path = "bin/head.rs"

[[bin]]
name = "_clear"
path = "bin/clear.rs"

[[bin]]
name = "_sleep"
path = "bin/sleep.rs"

[[bin]]
name = "_touch"
path = "bin/touch.rs"

[[bin]]
name = "_jell"
path = "bin/jell.rs"

[[bin]]
name = "_benchthruput"
path = "bin/bench_throughput.rs"

[[bin]]
name = "_benchfair"
path = "bin/bench_fairness.rs"

[[bin]]
name = "_benchlatency"
path = "bin/bench_latency.rs"

[[bin]]
name = "_benchiobound"
path = "bin/bench_iobound.rs"

[[bin]]
name = "_benchoverhed"
path = "bin/bench_overhead.rs"

[[bin]]
name = "_benchcpusym"
path = "bin/bench_cpusym.rs"

[[bin]]
name = "_benchsleepw"
path = "bin/bench_sleepw.rs"

[[bin]]
name = "_benchnewprc"
path = "bin/bench_newproc.rs"

[[bin]]
name = "_benchvdl"
path = "bin/bench_vdl.rs"

[[bin]]
name = "_benchepoch"
path = "bin/bench_epoch.rs"

[[bin]]
name = "_benchadapt"
path = "bin/bench_adapt.rs"

[[bin]]
name = "_benchadaptrev"
path = "bin/bench_adapt_rev.rs"

[[bin]]
name = "_benchfairhvy"
path = "bin/bench_fairhvy.rs"

[[bin]]
name = "_benchconvoy"
path = "bin/bench_convoy.rs"

[[bin]]
name = "_benchstarve"
path = "bin/bench_starve.rs"

[[bin]]
name = "_benchiosched"
path = "bin/bench_iosched.rs"

[[bin]]
name = "_benchvdlhvy"
path = "bin/bench_vdlhvy.rs"

[[bin]]
name = "_benchmaxproc"
path = "bin/bench_maxproc.rs"

[[bin]]
name = "_benchburst"
path = "bin/bench_burst.rs"

[[bin]]
name = "_benchphaseflip"
path = "bin/bench_phaseflip.rs"

[[bin]]
name = "_benchstarveio"
path = "bin/bench_starve_io.rs"

[dependencies]
libkernel = { workspace = true }

[build-dependencies]
libkernel = { workspace = true }
